### ISSUE TITLE
Remember pubkey / wallet address

### ISSUE THREAD

**Issue by DJPatron** [TAHCOINBLOCKCHAIN/tahcoin-blockchain#1]
Please implement wallet address or pubkey remembering mechanism, or refresh button in the wallet UI using simple cookies.
Copypasting pubkey each time you want to see your progress is truly exhausting practice.
Thanks!

**Comment by TAHCOINBLOCKCHAIN** [comment]
Thank you for your suggestion regarding the implementation of a wallet address or public key remembering mechanism in the Tahcoin wallet UI. We understand that the current process of copypasting the public key can be cumbersome, and we appreciate your feedback.

### Current Status

As you mentioned, the current client wallet will not be updated to include this feature. Instead, we are excited to announce that we are in the process of developing a new wallet that will support multiple cryptocurrencies, including Tahcoin. This new wallet aims to enhance user experience by incorporating functionalities such as:

- **Wallet Address/Pubkey Remembering**: Users will be able to save their wallet addresses and public keys for easy access.
- **Refresh Button**: A simple refresh button will allow users to quickly update their progress without needing to copypaste information repeatedly.
- **Multi-Coin Support**: The new wallet will facilitate transactions across various cryptocurrencies, making it a versatile tool for our users.

### Next Steps

We are committed to delivering a seamless experience for our users and will keep you updated on the development of the new wallet. Your feedback is invaluable in shaping our project, and we encourage you to continue sharing your thoughts.

Thank you for your understanding and support as we work towards these improvements! If you have any further suggestions or questions, please feel free to reach out.
