### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by psevdokounian** [TAHCOINBLOCKCHAIN/tahcoin-blockchain#2]
Selecting Number of Threads doing nothing. I tried to run 4 threads and 32.

Screenshot:

![tahtah](https://github.com/user-attachments/assets/a84639f0-c3e8-40f4-9aa0-4e3ec5589351)

**Comment by TAHCOINBLOCKCHAIN** [comment]
Keep threads at 1 and difficulty at 1 for optimal mining. No need for higher settings right now!
